[package]
name = "corn_game"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.corn_game]
opt-level = 1

[dependencies]
# NOTE: https://github.com/joseph-gio/bevy-trait-query/issues/77 breaks with bevy_ecs/track_change_detection
bevy = { version = "0.16.0", default-features = true, features = [
    "dynamic_linking", 
    "serialize", 
    "asset_processor", 
    "file_watcher", 
    "embedded_watcher", 
    "default_font", 
    "jpeg", 
    "bevy_remote",
    "webgl2",
    "web"
  ]}
# blenvy = { path = "./forks/Blenvy/crates/blenvy"}
bevy_skein = "0.2.1"
wgpu-types = "24"
wgpu = "24"
bevy-tnua = "0.24.0"
bevy-tnua-avian3d = "0.5.0"
avian3d = { version = "0.3.0", features = ["serialize"]}
lightyear = { version = "0.20.2", features = [
  "avian3d", 
  # "metrics", 
  "websocket",
  "webtransport",
  "udp"
]}
leafwing-input-manager = "0.17.0"
# bevy_edge_detection = "0.15.4"
bevy_easings = "0.16.0"
# bevy_asset_loader = "0.23.0"
bevy-trait-query = "0.16.0" 
bevy_editor_pls = "0.11"

serde = "*"
clap = {version = "4.5.38", features = ["derive"]}
rand = "0.9.0"
bytemuck = "1.14.1"
async-channel = "2.3.1"
uuid = "*"

image = "0.25.5"
prse = "1.2.1"
auto_enums = "0.8.5"
frunk = "0.4.3"
aligned-vec = "0.6.4"

[patch.crates-io]
bevy_editor_pls = { path = "forks/editor/crates/bevy_editor_pls/" }
bevy-inspector-egui = { path = "forks/editor/forks/bevy-inspector-egui/crates/bevy-inspector-egui" }
egui_dock = { path = "forks/editor/forks/egui-dock/" }
# transform-gizmo-bevy = { git = "https://github.com/ActuallyHappening/transform-gizmo" }

# bevy-tnua-avian3d = { path = "./forks/bevy-tnua/avian3d" }
# bevy-tnua-physics-integration-layer = { path = "./forks/bevy-tnua/physics-integration-layer" }

lightyear = { path = "forks/lightyear/lightyear" }
# bevy_skein = { path = "forks/skein" }
#avian3d = {git = "https://github.com/Jondolf/avian.git"}
