[package]
name = "corn_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.0", default-features = true, features=["dynamic_linking"]}
bevy-inspector-egui = "0.19.0"
rand = "0.8.5"
bytemuck = "1.14.0"
bevy_mod_debugdump = "0.8.0"
futures-lite = "1.13.0"
wgpu = "0.17.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
