[package]
name = "corn_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/RyanSpaker/bevy.git", branch = "main", default-features = true, features=["dynamic_linking", "asset_processor"]}
bevy-inspector-egui = "0.22.1"
rand = "0.8.5"
bytemuck = "1.14.1"
bevy_mod_debugdump = "0.9.0"
futures-lite = "2.2.0"
bitflags = "2.4.2"
wgpu = "0.19.1"
gltf = "1.4.0"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
